name: CI

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "assets/**"
      - "resume/**"
      - "Cargo.toml"
      - ".github/workflows/ci.yml"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Tests (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix Flake Environement
        uses: DeterminateSystems/determinate-nix-action@v3.17.2

      - uses: Swatinem/rust-cache@v2

      - name: cargo test
        run: cargo test

  clippy:
    name: Clippy (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix Flake Environement
        uses: DeterminateSystems/determinate-nix-action@v3.17.2

      - uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        run: cargo clippy -- -D warnings

  rustfmt:
    name: Rustfmt (nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix Flake Environement
        uses: DeterminateSystems/determinate-nix-action@v3.17.2

      - uses: Swatinem/rust-cache@v2

      - name: rustfmt --check
        run: cargo fmt --all --check

  build-and-publish:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - test
      - clippy
      - rustfmt
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Nix Flake Environement
        uses: DeterminateSystems/determinate-nix-action@v3.17.2

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Generate HTML and publish directory
        run: cargo run --release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          cname: cv.melois.dev
          force_orphan: true
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "chore: publish resume"
